# create instances
- hosts: localhost
  connection: local
  become: False
  gather_facts: False
  roles:
    - general-variables
  tasks:
    - name: assert input is correct
      assert:
        that:
          - aws_instance_type is defined
          - aws_service is defined
        msg: "USAGE: ansible-playbook -i inventories/<envname> playbooks/scale-up.yml -e 'rb_service=<service> rb_instance_type=<aws instance type> rb_instance_num=<number of instances>'"
    - name: create instances
        msg: "Now is the real thing"